#!/usr/bin/env python3
"""Alpha Pulse - Daily Market Scan & Advisory Generator"""
import json, subprocess, os
from datetime import datetime

QUANT_DIR = "/var/openclaw_users/matos/.openclaw/workspace/skills/quant_trader"
OUT_DIR = "/var/openclaw_users/matos/.openclaw/workspace/quant-advisory"

TICKERS = ["NVDA", "AAPL", "MSFT", "META", "TSLA", "AMD", "SPY", "QQQ", "PLTR", "SOFI", "GOOGL", "AMZN"]
DTE_OPTIONS = [14, 30, 60]

def run_scan():
    """Run full market scan using quant trader"""
    print("🔍 Running Alpha Pulse daily scan...")
    
    # Step 1: Technical scan
    result = subprocess.run(
        ["python3", f"{QUANT_DIR}/main.py", "--scan", "--tickers", ",".join(TICKERS)],
        capture_output=True, text=True, timeout=120
    )
    scan_output = result.stdout + result.stderr
    
    # Step 2: Options picks
    options_results = []
    for dte in DTE_OPTIONS:
        r = subprocess.run(
            ["python3", f"{QUANT_DIR}/options.py", "--scan", "--dte", str(dte)],
            capture_output=True, text=True, timeout=120
        )
        options_results.append({"dte": dte, "output": r.stdout + r.stderr})
    
    # Step 3: Compile report
    report = generate_report(scan_output, options_results)
    
    # Save
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_path = f"{OUT_DIR}/reports/{date_str}.md"
    os.makedirs(f"{OUT_DIR}/reports", exist_ok=True)
    with open(report_path, "w") as f:
        f.write(report)
    
    print(f"✅ Report saved: {report_path}")
    return report

def generate_report(scan, options):
    date_str = datetime.now().strftime("%B %d, %Y")
    report = f"""# 📊 Alpha Pulse — Daily Market Scan
**{date_str}**

---

## Market Overview
{scan[:1500]}

---

## Options Watchlist
"""
    for opt in options:
        report += f"\n### {opt['dte']}-Day Expiry\n```\n{opt['output'][:1000]}\n```\n"
    
    report += f"""
---
*Generated by Alpha Pulse — AI-Powered Trading Advisory*
*Disclaimer: For informational purposes only. Not financial advice.*
"""
    return report

def send_alert(report):
    """Send summary via Telegram"""
    summary = report[:3000]
    print(f"\n📨 Telegram alert ready ({len(summary)} chars)")
    print("---")
    print(summary[:500])
    print("...")

if __name__ == "__main__":
    report = run_scan()
    send_alert(report)
